# -*- coding: utf-8 -*-
"""clean_energy_investment_opportunity_rank P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLOlevyQ9hNgWlFU1BTO0oi04BcddiDX
"""

import pandas as pd
import numpy as np
import plotly.express as px
from google.colab import files

upload = files.upload()
df = pd.read_csv('complete_renewable_energy_dataset.csv')

#check duplicate value
duplicates = df.duplicated(subset=['GDP']).sum()
duplicates

"""#macro understanding the investment by energy type over year"""

df.head()

df.isnull().sum()

fig= px.box(df, x='Energy Type', y='Investments (USD)')
fig.update_layout
fig.show()

#Total investment by energy type each year between 2019-2023
invest_by_type_year = df.groupby(['Year', 'Energy Type'])['Investments (USD)'].sum().reset_index()
invest_by_type_year_filtered = invest_by_type_year[(invest_by_type_year['Year'] >= 2019) & (invest_by_type_year['Year'] <= 2023)]

df_display = invest_by_type_year_filtered.copy()
df_display['Investments (USD)'] = (df_display['Investments (USD)'] / 1e9).round(2).astype(str) + ' B'

display(df_display)

fig = px.line(invest_by_type_year_filtered, x='Year', y='Investments (USD)', color='Energy Type',
              title='Total Investments over Time by Energy Type')

fig.show()

# Pick the data I need
list_country_dfs = []
for country in df['Country'].unique():
    country_df = df.loc[(df['Country'] == country) & (df['Year']>=2019) &(df['Year']<=2023),
     ['Country', 'Energy Type', 'Year', 'Investments (USD)']].sort_values(by='Year')
    list_country_dfs.append(country_df)


# Display the first few rows of the dataframe for the first country as an example
if list_country_dfs:
    print(f"Data for {df['Country'].unique()[0]} in year between 2019-2023:")
    display(list_country_dfs[0].head())
else:
    print("No countries found in the dataframe.")

#investment trend by year by country (visualize)
for country_df in list_country_dfs:
    country_name = country_df['Country'].iloc[0]
    invest_by_type_year = country_df.groupby(['Year', 'Energy Type'])['Investments (USD)'].sum().reset_index()

    fig = px.line(invest_by_type_year, x='Year', y='Investments (USD)', color='Energy Type',
                  title=f'Investments over Time for {country_name} by Energy Type')
    fig.show()

"""# Task
Analyze renewable energy investment data from "renewable_energy_investments.csv" and "country_population.csv" to identify top emerging markets. Calculate CAGR for 2019-2023, assess market saturation using capacity per capita and a saturation index, and create a ranked table of top 10-15 emerging markets with an investment opportunity score. Finally, print the ranking table and the top 10 sweet spot markets.

## Data preparation

### Subtask:
Filter the dataset for the years 2019-2023 and ensure year-to-year data is available for CAGR calculation.

**Reasoning**:
Filter the dataframe for the years 2019-2023 and ensure year-to-year data is available for CAGR calculation by checking for 5 unique years per country and energy type, and then filter the dataframe to keep only those groups.
"""

df_filtered_years = df[(df['Year'] >= 2019) & (df['Year'] <= 2023)].copy()

year_counts = df_filtered_years.groupby(['Country', 'Energy Type'])['Year'].nunique().reset_index()

complete_data_groups = year_counts[year_counts['Year'] == 5]

complete_groups_list = list(zip(complete_data_groups['Country'], complete_data_groups['Energy Type']))

df_filtered = df_filtered_years[df_filtered_years.apply(lambda row: (row['Country'], row['Energy Type']) in complete_groups_list, axis=1)].copy()

display(df_filtered.head())

"""## Calculate cagr

### Subtask:
Calculate the Compound Annual Growth Rate of investments for each country and energy type for the 2019-2023 period, handling missing years appropriately.

**Reasoning**:
Group the filtered data by country and energy type and calculate the sum of investments for each year within those groups.
"""

invest_by_type_year_filtered = df_filtered.groupby(['Country', 'Energy Type', 'Year'])['Investments (USD)'].sum().reset_index()
display(invest_by_type_year_filtered.head())

"""**Reasoning**:
Pivot the filtered dataframe to have 'Country' and 'Energy Type' as index, 'Year' as columns, and 'Investments (USD)' as values to prepare for CAGR calculation, then calculate CAGR for the 2019-2023 period.


"""

#transform data to pivot table with each year as columns title
invest_pivot = invest_by_type_year_filtered.pivot_table(index=['Country', 'Energy Type'], columns='Year', values='Investments (USD)')

# Calculate CAGR
cagr_results = ((invest_pivot[2023] / invest_pivot[2019])**(1/5) - 1) * 100

# Convert to DataFrame for easier handling and add a meaningful column name
cagr_results = cagr_results.reset_index(name='CAGR (2019-2023)')

display(cagr_results.head())

"""## Market saturation analysis

### Subtask:
Compute the installed capacity per capita for each country in the latest year (2023) and calculate a market saturation index.

**Reasoning**:
Filter the DataFrame for the year 2023, calculate the total installed capacity and population per country, compute capacity per capita, and then calculate a market saturation index using min-max normalization.
"""

df_2023=df[df['Year']==2023].copy()
# Aggregate by country
market_saturation = df_2023.groupby('Country').agg({
    'Installed Capacity (MW)': 'sum',
    'Proportion of Energy from Renewables': 'first',
    'Population': 'first',
    'GDP': 'first'
}).reset_index()

# Rename for clarity
market_saturation.rename(columns={
    'Proportion of Energy from Renewables': 'Market Saturation (%)'
}, inplace=True)

# Calculate Capacity Per Capita (for additional context)
market_saturation['Capacity Per Capita (MW/person)'] = (
    market_saturation['Installed Capacity (MW)'] /
    market_saturation['Population']
)

# Categorize markets by saturation level
def categorize_market(saturation):
    if saturation < 20:
        return 'Emerging (<20%)'
    elif saturation < 40:
        return 'Developing (20-40%)'
    elif saturation < 60:
        return 'Growing (40-60%)'
    elif saturation < 80:
        return 'Maturing (60-80%)'
    else:
        return 'Saturated (>80%)'

market_saturation['Market Category'] = market_saturation['Market Saturation (%)'].apply(categorize_market)

# Sort by Market Saturation
market_saturation_sorted = market_saturation.sort_values('Market Saturation (%)', ascending=False)

# Display results
print("=== MARKET SATURATION ANALYSIS ===\n")
print("Market Saturation = Proportion of Energy from Renewables\n")
display(market_saturation_sorted[[
    'Country',
    'Installed Capacity (MW)',
    'Market Saturation (%)',
    'Capacity Per Capita (MW/person)',
    'Market Category'
]].head(15))

# Summary Statistics
print("\n=== SUMMARY STATISTICS ===")
print(f"Average Market Saturation: {market_saturation['Market Saturation (%)'].mean():.2f}%")
print(f"Median Market Saturation: {market_saturation['Market Saturation (%)'].median():.2f}%")
print(f"Highest Saturation: {market_saturation['Market Saturation (%)'].max():.2f}%")
print(f"Lowest Saturation: {market_saturation['Market Saturation (%)'].min():.2f}%")

print("\n=== MARKET CATEGORY DISTRIBUTION ===")
print(market_saturation['Market Category'].value_counts().sort_index())

# Identify high growth potential markets (low saturation)
print("\n=== TOP 10 MARKETS WITH GROWTH POTENTIAL (Lowest Saturation) ===")
low_saturation = market_saturation_sorted.sort_values('Market Saturation (%)', ascending=True)
display(low_saturation[['Country', 'Market Saturation (%)', 'Installed Capacity (MW)']].head(10))

# ===================================================================
# STEP 1: Calculate CAGR by Country AND Energy Type
# ===================================================================
# Transform data to pivot table with each year as columns
invest_pivot = invest_by_type_year_filtered.pivot_table(
    index=['Country', 'Energy Type'],
    columns='Year',
    values='Investments (USD)'
)

# Calculate CAGR for investments
cagr_results = ((invest_pivot[2023] / invest_pivot[2019])**(1/5) - 1) * 100
cagr_results = cagr_results.reset_index(name='CAGR (%)')

# Keep Country AND Energy Type (no aggregation)
cagr_by_country_type = cagr_results[['Country', 'Energy Type', 'CAGR (%)']].copy()

print("=== CAGR BY COUNTRY AND ENERGY TYPE ===")
display(cagr_by_country_type.sort_values('CAGR (%)', ascending=False).head(10))

# ===================================================================
# STEP 2: Calculate Market Saturation by Country AND Energy Type
# ===================================================================
df_2023 = df[df['Year'] == 2023].copy()

# Group by Country AND Energy Type
market_saturation = df_2023.groupby(['Country', 'Energy Type']).agg({
    'Installed Capacity (MW)': 'sum',
    'Production (GWh)': 'sum',
    'Energy Consumption': 'first',
    'Population': 'first',
    'GDP': 'first'
}).reset_index()

# Calculate energy type specific saturation
# Market Saturation = Production from this energy type / Total Energy Consumption * 100
market_saturation['Market Saturation (%)'] = (
    market_saturation['Production (GWh)'] /
    market_saturation['Energy Consumption']
) * 100

# Cap saturation at 100% (some might exceed due to exports)
market_saturation['Market Saturation (%)'] = market_saturation['Market Saturation (%)'].clip(upper=100)

# Calculate Capacity Per Capita
market_saturation['Capacity Per Capita (MW/person)'] = (
    market_saturation['Installed Capacity (MW)'] /
    market_saturation['Population']
)

print("\n=== MARKET SATURATION BY COUNTRY AND ENERGY TYPE ===")
display(market_saturation.sort_values('Market Saturation (%)', ascending=False).head(10))

# ===================================================================
# STEP 3: Merge CAGR and Market Saturation
# ===================================================================
investment_analysis = cagr_by_country_type.merge(
    market_saturation,
    on=['Country', 'Energy Type'],
    how='inner'
)

print(f"\n=== MERGED DATA ===")
print(f"Total country-energy type combinations: {len(investment_analysis)}")
print(f"Unique countries: {investment_analysis['Country'].nunique()}")
print(f"Unique energy types: {investment_analysis['Energy Type'].nunique()}")

# ===================================================================
# STEP 4: Normalize Metrics (Min-Max Normalization)
# ===================================================================
# Normalize CAGR (0 to 1 scale)
investment_analysis['CAGR_norm'] = (
    (investment_analysis['CAGR (%)'] - investment_analysis['CAGR (%)'].min()) /
    (investment_analysis['CAGR (%)'].max() - investment_analysis['CAGR (%)'].min())
)

# Normalize Saturation (0 to 1 scale)
investment_analysis['Saturation_norm'] = (
    (investment_analysis['Market Saturation (%)'] - investment_analysis['Market Saturation (%)'].min()) /
    (investment_analysis['Market Saturation (%)'].max() - investment_analysis['Market Saturation (%)'].min())
)

# Handle any NaN values from normalization (if all values are the same)
investment_analysis['CAGR_norm'].fillna(0, inplace=True)
investment_analysis['Saturation_norm'].fillna(0, inplace=True)

# ===================================================================
# STEP 5: Calculate Weighted Investment Opportunity Score
# ===================================================================
# Formula: 60% weight on CAGR growth, 40% weight on low saturation (room to grow)
investment_analysis['Investment Opportunity Score'] = (
    0.6 * investment_analysis['CAGR_norm'] +
    0.4 * (1 - investment_analysis['Saturation_norm'])
)

# Handle negative CAGR (declining markets) - penalize them
investment_analysis.loc[
    investment_analysis['CAGR (%)'] < 0,
    'Investment Opportunity Score'
] = investment_analysis.loc[
    investment_analysis['CAGR (%)'] < 0,
    'Investment Opportunity Score'
] * 0.5  # Reduce score by 50% for negative growth

# ===================================================================
# STEP 6: Scale Score to 0-100 for easier interpretation
# ===================================================================
investment_analysis['Normalized Score (0-100)'] = (
    investment_analysis['Investment Opportunity Score'] * 100
)

# ===================================================================
# STEP 7: Create Investment Ranking by Country + Energy Type
# ===================================================================
investment_analysis['Investment Rank'] = investment_analysis['Normalized Score (0-100)'].rank(
    ascending=False,
    method='min'
).astype(int)

# ===================================================================
# STEP 8: Categorize Investment Opportunity
# ===================================================================
def categorize_opportunity(score):
    if score >= 80:
        return '⭐⭐⭐ Excellent'
    elif score >= 60:
        return '⭐⭐ Very Good'
    elif score >= 40:
        return '⭐ Good'
    elif score >= 20:
        return 'Moderate'
    else:
        return 'Limited'

investment_analysis['Opportunity Category'] = investment_analysis['Normalized Score (0-100)'].apply(categorize_opportunity)

# ===================================================================
# STEP 9: Sort by Investment Rank
# ===================================================================
investment_ranking = investment_analysis.sort_values('Investment Rank', ascending=True)

# ===================================================================
# STEP 10: Display Results
# ===================================================================
print("\n" + "="*100)
print("=== TOP 25 INVESTMENT OPPORTUNITIES (Ranked by Country + Energy Type) ===")
print("="*100)
print("\nScore Formula: 0.6 × Normalized_CAGR + 0.4 × (1 - Normalized_Saturation)")
print("Higher scores = Fast growth + Low saturation = Best investment potential\n")

display(investment_ranking[[
    'Investment Rank',
    'Country',
    'Energy Type',
    'CAGR (%)',
    'Market Saturation (%)',
    'Investment Opportunity Score',
    'Normalized Score (0-100)',
    'Opportunity Category',
    'Installed Capacity (MW)',
    'GDP'
]].head(25))

# ===================================================================
# STEP 11: Category Breakdown
# ===================================================================
print("\n=== INVESTMENT OPPORTUNITY DISTRIBUTION ===")
print(investment_analysis['Opportunity Category'].value_counts().sort_index(ascending=False))

print("\n=== OPPORTUNITIES BY ENERGY TYPE ===")
energy_type_breakdown = investment_analysis.groupby('Energy Type').agg({
    'Normalized Score (0-100)': 'mean',
    'CAGR (%)': 'mean',
    'Market Saturation (%)': 'mean'
}).round(2)
display(energy_type_breakdown.sort_values('Normalized Score (0-100)', ascending=False))

# ===================================================================
# STEP 12: Top Opportunities by Energy Type
# ===================================================================
print("\n=== TOP 5 OPPORTUNITIES BY ENERGY TYPE ===")
for energy_type in investment_analysis['Energy Type'].unique():
    print(f"\n{energy_type.upper()}:")
    top_by_type = investment_ranking[investment_ranking['Energy Type'] == energy_type].head(5)
    display(top_by_type[['Investment Rank', 'Country', 'CAGR (%)', 'Market Saturation (%)', 'Normalized Score (0-100)']])

# ===================================================================
# STEP 13: Quadrant Analysis
# ===================================================================
print("\n=== QUADRANT ANALYSIS ===")
median_cagr = investment_analysis['CAGR (%)'].median()
median_saturation = investment_analysis['Market Saturation (%)'].median()

def assign_quadrant(row):
    if row['CAGR (%)'] >= median_cagr and row['Market Saturation (%)'] < median_saturation:
        return 'Q1: High Growth + Low Saturation (🔥 BEST)'
    elif row['CAGR (%)'] >= median_cagr and row['Market Saturation (%)'] >= median_saturation:
        return 'Q2: High Growth + High Saturation'
    elif row['CAGR (%)'] < median_cagr and row['Market Saturation (%)'] < median_saturation:
        return 'Q3: Low Growth + Low Saturation'
    else:
        return 'Q4: Low Growth + High Saturation (⚠️ AVOID)'

investment_analysis['Quadrant'] = investment_analysis.apply(assign_quadrant, axis=1)

print("\nQuadrant Distribution:")
print(investment_analysis['Quadrant'].value_counts())

print("\n🔥 BEST OPPORTUNITIES (Q1 - High Growth + Low Saturation):")
q1_markets = investment_analysis[investment_analysis['Quadrant'].str.contains('Q1')].sort_values('Normalized Score (0-100)', ascending=False)
display(q1_markets[['Investment Rank', 'Country', 'Energy Type', 'CAGR (%)', 'Market Saturation (%)', 'Normalized Score (0-100)']].head(15))

# ===================================================================
# STEP 14: Summary Statistics
# ===================================================================
print("\n=== SUMMARY STATISTICS ===")
print(f"Average Investment Score: {investment_analysis['Normalized Score (0-100)'].mean():.2f}")
print(f"Median Investment Score: {investment_analysis['Normalized Score (0-100)'].median():.2f}")
print(f"Top Score: {investment_analysis['Normalized Score (0-100)'].max():.2f}")
print(f"Opportunities with Excellent Rating: {len(investment_analysis[investment_analysis['Normalized Score (0-100)'] >= 80])}")
print(f"Opportunities with Very Good+ Rating: {len(investment_analysis[investment_analysis['Normalized Score (0-100)'] >= 60])}")

# ===================================================================
# VIZ 1: Top 15 Investment Opportunities - Simple Bar Chart
# ===================================================================
top_15 = investment_ranking.head(15).copy()

# Create combined label with rank
top_15['Label'] = (
    '#' + top_15['Investment Rank'].astype(str) + ' - ' +
    top_15['Country'] + ' (' + top_15['Energy Type'] + ')'
)

fig1 = px.bar(
    top_15,
    x='Label',
    y='Normalized Score (0-100)',
    color='Energy Type',
    title='Top 15 Investment Opportunities (Ranked)',
    labels={'Label': '', 'Normalized Score (0-100)': 'Investment Score'},
    text='Normalized Score (0-100)'
)

fig1.update_traces(texttemplate='%{text:.1f}', textposition='outside')
fig1.update_layout(
    xaxis_tickangle=-45,
    height=500,
    xaxis={'categoryorder':'total descending'}
)
fig1.show()

# ===================================================================
# VIZ 2: CAGR vs Saturation - Scatter Plot (Top 30)
# ===================================================================
top_30 = investment_ranking.head(30).copy()

fig2 = px.scatter(
    top_30,
    x='Market Saturation (%)',
    y='CAGR (%)',
    size='Normalized Score (0-100)',
    color='Energy Type',
    hover_data=['Country', 'Investment Rank'],
    title='Growth vs Saturation - Top 30 Opportunities',
    text='Country'
)

fig2.update_traces(textposition='top center', textfont_size=8)
fig2.update_layout(height=600)
fig2.show()

# ===================================================================
# VIZ 3: Best Opportunities by Energy Type
# ===================================================================
# Get top 3 per energy type
top_by_energy = investment_ranking.groupby('Energy Type').head(3).reset_index(drop=True)
top_by_energy['Label'] = top_by_energy['Country']

fig3 = px.bar(
    top_by_energy,
    x='Label',
    y='Normalized Score (0-100)',
    color='Energy Type',
    facet_col='Energy Type',
    title='Top 3 Opportunities by Energy Type',
    labels={'Normalized Score (0-100)': 'Score'}
)

fig3.update_xaxes(tickangle=-45)
fig3.update_layout(height=500, showlegend=False)
fig3.show()

"""## Business Insights from Renewable Energy Investment Analysis

Based on the analysis of renewable energy investments, CAGR, market saturation, and the ranking of emerging markets, here are some key business insights:

1.  **Identified "Sweet Spot" Markets for Investment:** The ranking table and the identification of the top 10 sweet spot markets (those with low saturation and high investment opportunity scores) provide clear targets for potential investment. Focusing on these markets could yield higher returns due to their growth potential and less crowded landscapes.
2.  **Varied Growth Trajectories Across Countries and Energy Types:** The CAGR analysis revealed significant differences in investment growth rates across countries and energy types. This highlights the importance of a granular approach to investment strategy, tailoring it to specific energy types within promising countries rather than a broad-brush approach.
3.  **Market Saturation as a Key Factor:** The market saturation analysis, using capacity per capita and a saturation index, offers a crucial perspective beyond just growth rates. Investing in markets with lower saturation may present greater opportunities for market penetration and long-term growth before facing intense competition.
4.  **Data-Driven Prioritization:** The ranking table, incorporating CAGR, saturation, and an overall investment opportunity score, provides a data-driven framework for prioritizing potential markets. This allows for a more objective assessment of where to allocate resources for maximum impact.
5.  **Potential for Further Investigation:** While the analysis identifies promising markets, further due diligence is required. Understanding the specific government policies, regulatory environments, and local market dynamics within these sweet spot markets will be crucial before making significant investment decisions.

## Assessment of Output Comprehensiveness

The current output includes:

*   Data loading and initial checks.
*   Analysis of total investment by energy type over the years (2019-2023).
*   Calculation of CAGR by country and energy type.
*   Market saturation analysis (capacity per capita and saturation index).
*   A complete ranking table of countries based on investment opportunity.
*   Identification and display of the top 10 sweet spot markets.
*   A summary markdown cell outlining the key findings and next steps.

The outputs comprehensively address the initial task of identifying top emerging markets based on the specified criteria. The ranking table and the list of sweet spot markets directly answer the core objective. The supporting analysis (CAGR and saturation) provides the foundation for these rankings.

To make the output even more comprehensive and easier to interpret for stakeholders, consider adding:

*   **Visualizations:** While some plots were generated earlier (e.g., line plots of investments over time), incorporating visualizations of the ranking table data (e.g., a bar chart of investment opportunity scores for the top markets, or a scatter plot showing CAGR vs. Saturation Index) would significantly enhance understanding.
*   **Detailed Explanation of Metrics:** A more detailed explanation of how CAGR, Market Saturation Index, and Investment Opportunity Score are calculated and what they signify in the context of renewable energy investment would be beneficial for a wider audience.
*   **Limitations of the Analysis:** Briefly mentioning any limitations of the analysis (e.g., reliance on historical data for projections, potential data quality issues, factors not included in the dataset) adds to the transparency and comprehensiveness.
*   **Recommendations:** Explicitly stating recommendations for action based on the insights (e.g., "Recommend further investigation into the regulatory landscape of Canada and the USA for Hydro and Geothermal energy investments, respectively").

Overall, the current output provides the essential information required by the task. Adding more context and visualizations would elevate its comprehensiveness for a business audience.

## Video Recording Topics and Pitch Lines

Here are some potential topics for video recordings based on our analysis, along with draft pitch lines:

**Potential Video Topics:**

1.  **Uncovering Renewable Energy Investment Hotspots:** A deep dive into which countries and energy types offer the best investment potential based on growth and market saturation.
2.  **CAGR vs. Saturation:** Understanding the two key metrics for identifying emerging renewable energy markets.
3.  **The Top 10 "Sweet Spot" Markets:** A closer look at the markets with high growth and low saturation, and why they are attractive for investors.
4.  **Beyond the Surface:** Analyzing factors influencing renewable energy investment opportunities (e.g., government policies, GDP, population).
5.  **Data-Driven Market Analysis:** Demonstrating how data analysis can guide strategic investment decisions in the renewable energy sector.
6.  **Energy Type Focus:** Exploring the investment landscape and opportunities within specific renewable energy types (Solar, Wind, Hydro, Geothermal, Biomass).

**Draft Video Pitch Lines:**

1.  "Looking to invest in renewable energy? Discover the hidden gems and avoid saturated markets with our data-driven analysis."
2.  "Is the renewable energy boom real? We crunch the numbers on investment growth and market saturation to reveal the top emerging opportunities."
3.  "Don't invest blind! Learn how to identify the renewable energy 'sweet spots' with the highest potential for return."
4.  "Join us as we break down the complex world of renewable energy investments using real data and powerful analytics."
5.  "From CAGR to market saturation: Get the key insights you need to make smart investment decisions in the fast-growing renewable energy sector."

**Reasoning**:
Merge the CAGR and capacity data, categorize saturation, calculate an investment score, and rank the countries. Then, select and reorder the columns for the final ranking table.

**Reasoning**:
Print the complete ranking table, then filter the top 10 sweet spot markets and print the filtered table.
"""

#ranking_table.to_csv('ranking_table.csv', index=False)

#from google.colab import files
#files.download('ranking_table.csv')

"""## Summary:

### Data Analysis Key Findings

*   The analysis successfully filtered the renewable energy investment data for the years 2019-2023, ensuring complete year-over-year data for CAGR calculation for each Country and Energy Type combination.
*   Compound Annual Growth Rate (CAGR) for the period 2019-2023 was calculated for each country and energy type combination.
*   Market saturation was assessed by calculating installed capacity per capita and a normalized market saturation index for each country in 2023.
*   Countries were categorized into 'Low', 'Medium', or 'High' saturation based on their market saturation index.
*   An Investment Opportunity Score was calculated for each country, prioritizing higher CAGR and lower market saturation.
*   A final ranking table was generated, ordering countries by their Investment Opportunity Score and including key metrics like Rank, Country, CAGR, Installed Capacity, Capacity Per Capita, Market Saturation Index, Saturation Category, and Investment Opportunity Score.
*   The top 10 "sweet spot" markets were identified as those with a 'Low' saturation category and a high Investment Opportunity Score.

### Insights or Next Steps

*   Focus investment strategies on the identified top 10 "sweet spot" markets with low saturation and high investment opportunity scores for potentially higher returns.
*   Further investigate the specific energy types driving the high CAGR in the identified sweet spot markets to tailor investment accordingly.

## Business Insights from Renewable Energy Investment Analysis

Based on the analysis of renewable energy investments, CAGR, market saturation, and the ranking of emerging markets, here are some key business insights:

1.  **Identified "Sweet Spot" Markets for Investment:** The ranking table and the identification of the top 10 sweet spot markets (those with low saturation and high investment opportunity scores) provide clear targets for potential investment. Focusing on these markets could yield higher returns due to their growth potential and less crowded landscapes.
2.  **Varied Growth Trajectories Across Countries and Energy Types:** The CAGR analysis revealed significant differences in investment growth rates across countries and energy types. This highlights the importance of a granular approach to investment strategy, tailoring it to specific energy types within promising countries rather than a broad-brush approach.
3.  **Market Saturation as a Key Factor:** The market saturation analysis, using capacity per capita and a saturation index, offers a crucial perspective beyond just growth rates. Investing in markets with lower saturation may present greater opportunities for market penetration and long-term growth before facing intense competition.
4.  **Data-Driven Prioritization:** The ranking table, incorporating CAGR, saturation, and an overall investment opportunity score, provides a data-driven framework for prioritizing potential markets. This allows for a more objective assessment of where to allocate resources for maximum impact.
5.  **Potential for Further Investigation:** While the analysis identifies promising markets, further due diligence is required. Understanding the specific government policies, regulatory environments, and local market dynamics within these sweet spot markets will be crucial before making significant investment decisions.

## Assessment of Output Comprehensiveness

The current output includes:

*   Data loading and initial checks.
*   Analysis of total investment by energy type over the years (2019-2023).
*   Calculation of CAGR by country and energy type.
*   Market saturation analysis (capacity per capita and saturation index).
*   A complete ranking table of countries based on investment opportunity.
*   Identification and display of the top 10 sweet spot markets.
*   A summary markdown cell outlining the key findings and next steps.

The outputs comprehensively address the initial task of identifying top emerging markets based on the specified criteria. The ranking table and the list of sweet spot markets directly answer the core objective. The supporting analysis (CAGR and saturation) provides the foundation for these rankings.

To make the output even more comprehensive and easier to interpret for stakeholders, consider adding:

*   **Visualizations:** While some plots were generated earlier (e.g., line plots of investments over time), incorporating visualizations of the ranking table data (e.g., a bar chart of investment opportunity scores for the top markets, or a scatter plot showing CAGR vs. Saturation Index) would significantly enhance understanding.
*   **Detailed Explanation of Metrics:** A more detailed explanation of how CAGR, Market Saturation Index, and Investment Opportunity Score are calculated and what they signify in the context of renewable energy investment would be beneficial for a wider audience.
*   **Limitations of the Analysis:** Briefly mentioning any limitations of the analysis (e.g., reliance on historical data for projections, potential data quality issues, factors not included in the dataset) adds to the transparency and comprehensiveness.
*   **Recommendations:** Explicitly stating recommendations for action based on the insights (e.g., "Recommend further investigation into the regulatory landscape of Canada and the USA for Hydro and Geothermal energy investments, respectively").

Overall, the current output provides the essential information required by the task. Adding more context and visualizations would elevate its comprehensiveness for a business audience.

## Visualizing Ranking Table Data

### Subtask:
Create a bar chart to visualize the Investment Opportunity Score for the top markets from the ranking table.

**Reasoning**:
Generate a bar chart using Plotly Express to display the Investment Opportunity Score for the top markets, using 'Country' and 'Energy Type' for the x-axis and 'Investment Opportunity Score' for the y-axis.

#################
new epoisode: ai generate is good but lack of insight and often odd
*compare this and original code
*mention Patric said in coursea
"""